### ISSUE TITLE
是否考虑下linux环境日志的管理？

### ISSUE THREAD

**Issue by lenosp** [xuxiaoxiao-xxx/ChatApi-QQ#4]
当运行在linux环境时候，一般都后台运行，以日志的形式保存记录，是否有必要集成日志以及以日志的形式保存运行记录，我感觉相对于System.out.println来说更好些。如果有必要，我会pull request。

**Comment by lenosp** [comment]
![image](https://user-images.githubusercontent.com/18375648/48602525-5d146880-e9ae-11e8-864c-e3cc834b958d.png)

**Comment by xuxiaoxiao-xxx** [comment]
日志用的是jdk自带的日志工具，在生成QQClient对象时可以传入自己的FileHandler，来将日志写入相应的文件，能够满足需求。暂无修改成其他日志工具的必要。

**Comment by lenosp** [comment]
好的，谢谢
