### ISSUE TITLE
problem about getvfwebqq

### ISSUE THREAD

**Issue by yearchan** [xuxiaoxiao-xxx/ChatApi-QQ#5]
now, a problem is showing. which is in the QQAPI.java --> getvfwebqq functions. today, i had tried to startup my qq bot. the exception about 'java.lang.IllegalStateException' showed. i tried troubleshot the problem. which is get the following response in getvfwebqq method. can you pls try to fix it? thank you.

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>stgw/1.3.6.2_1.13.5</center>
</body>
</html>

**Comment by lenosp** [comment]
Can you describe it in more detail, or give me your email?Maybe I can help you.

**Comment by yearchan** [comment]
> Can you describe it in more detail, or give me your email?Maybe I can help you.

it is ok now. which is the protocal changed from http to https.  and now, all the url changed to https. it work!

**Comment by xuxiaoxiao-xxx** [comment]
thank you for your report.

**Comment by yearchan** [comment]
> thank you for your report.

you are welcome
